kind = "web"
previewPath = "/"
title = "SJM Social Media"
version = "1.0.0"
id = "artifacts/sjm"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23136

[services.development]
run = "pnpm --filter @workspace/sjm run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sjm", "run", "build" ]
publicDir = "artifacts/sjm/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23136"
BASE_PATH = "/"
